# Configuração por modalidade — regras isoladas, sem alterar engines existentes.

MODALITIES = {
    "lotofacil": {
        "key": "lotofacil",
        "nome": "Lotofácil",
        "porta": 5152,
        "loader": "lotofacil",
        "service_import": ("services.analise_lotofacil_service", "AnaliseLotofacilService", "calcular_atrasos_absolutos"),
        "total": 25,
        "dezena_min": 1,
        "dezena_max": 25,
        "pick_default": 15,
        "pick_min": 15,
        "pick_max": 20,
        "sorteadas": 15,
        "extra": None,
        "dezena_badge_style": "background:var(--accent,#930089);color:var(--on-accent,#fff);border:2px solid var(--primary,#672666);font-weight:700;",
        "export_join": " ",
    },
    "supersete": {
        "key": "supersete",
        "nome": "Super Sete",
        "porta": 5160,
        "loader": "supersete_colunas",
        "service_import": ("services.analise_supersete_service", "AnaliseSuperSeteService", "analise_por_coluna"),
        "total": 10,
        "dezena_min": 0,
        "dezena_max": 9,
        "pick_default": 7,
        "pick_min": 7,
        "pick_max": 7,
        "sorteadas": 7,
        "extra": None,
        "dezena_badge_style": "background:#198754;color:#fff;border:2px solid #146c43;font-weight:700;",
        "export_join": "",
        "export_is_columns": True,
    },
    "lotomania": {
        "key": "lotomania",
        "nome": "Lotomania",
        "porta": 5154,
        "loader": "standard",
        "service_import": ("services.analise_lotomania_service", "AnaliseLotomaniaService", "analise_geral"),
        "total": 100,
        "dezena_min": 0,
        "dezena_max": 99,
        "pick_default": 50,
        "pick_min": 50,
        "pick_max": 50,
        "sorteadas": 20,
        "extra": None,
        "dezena_badge_style": "background:#e67e22;color:#fff;border:2px solid #d35400;font-weight:700;",
        "export_join": " ",
    },
    "quina": {
        "key": "quina",
        "nome": "Quina",
        "porta": 5155,
        "loader": "standard",
        "service_import": ("services.analise_quina_service", "AnaliseQuinaService", "analise_geral"),
        "total": 80,
        "dezena_min": 1,
        "dezena_max": 80,
        "pick_default": 5,
        "pick_min": 5,
        "pick_max": 15,
        "sorteadas": 5,
        "extra": None,
        "dezena_badge_style": "background:#2600fc;color:#fff;border:2px solid #1a0080;font-weight:700;",
        "export_join": " ",
    },
    "megasena": {
        "key": "megasena",
        "nome": "Mega-Sena",
        "porta": 5156,
        "loader": "standard",
        "service_import": ("services.analise_megasena_service", "AnaliseMegaSenaService", "analise_geral"),
        "total": 60,
        "dezena_min": 1,
        "dezena_max": 60,
        "pick_default": 6,
        "pick_min": 6,
        "pick_max": 20,
        "sorteadas": 6,
        "extra": None,
        "dezena_badge_style": "background:#ffd700;color:#000;border:2px solid #ffa500;font-weight:700;",
        "export_join": " ",
    },
    "maismilionaria": {
        "key": "maismilionaria",
        "nome": "+Milionária",
        "porta": 5157,
        "loader": "maismilionaria",
        "service_import": ("services.analise_maismilionaria_service", "AnaliseMaisMilionariaService", "analise_geral"),
        "total": 50,
        "dezena_min": 1,
        "dezena_max": 50,
        "pick_default": 6,
        "pick_min": 6,
        "pick_max": 12,
        "sorteadas": 6,
        "extra": "trevo",
        "trevo_total": 6,
        "trevo_pick": 2,
        "trevo_pick_min": 2,
        "trevo_pick_max": 6,
        "dezena_badge_style": "background:#0d6efd;color:#fff;border:2px solid #084298;font-weight:700;",
        "trevo_badge_style": "background:#6f42c1;color:#fff;border:2px solid #59359a;font-weight:700;",
        "export_join": " ",
    },
    "duplasena": {
        "key": "duplasena",
        "nome": "Dupla Sena",
        "porta": 5158,
        "loader": "standard",
        "service_import": ("services.analise_duplasena_service", "AnaliseDuplaSenaService", "analise_geral"),
        "total": 50,
        "dezena_min": 1,
        "dezena_max": 50,
        "pick_default": 6,
        "pick_min": 6,
        "pick_max": 15,
        "sorteadas": 6,
        "extra": None,
        "dezena_badge_style": "background:#dc3545;color:#fff;border:2px solid #b02a37;font-weight:700;",
        "export_join": " ",
    },
    "timemania": {
        "key": "timemania",
        "nome": "Timemania",
        "porta": 5159,
        "loader": "timemania",
        "service_import": ("services.analise_timemania_service", "AnaliseTimemaniaSService", "analise_geral"),
        "total": 80,
        "dezena_min": 1,
        "dezena_max": 80,
        "pick_default": 10,
        "pick_min": 10,
        "pick_max": 10,
        "sorteadas": 7,
        "extra": "time",
        "dezena_badge_style": "background:#f1c40f;color:#1a1a1a;border:2px solid #d4ac0d;font-weight:700;",
        "export_join": " ",
    },
    "diadesorte": {
        "key": "diadesorte",
        "nome": "Dia de Sorte",
        "porta": 5153,
        "loader": "diadesorte",
        "service_import": ("services.analise_diadesorte_service", "AnaliseDiaDeSorteService", "analise_geral"),
        "total": 31,
        "dezena_min": 1,
        "dezena_max": 31,
        "pick_default": 7,
        "pick_min": 7,
        "pick_max": 15,
        "sorteadas": 7,
        "extra": "mes",
        "dezena_badge_style": "background:#ffd700;color:#000;border:2px solid #ffa500;font-weight:700;",
        "export_join": " ",
        "meses_api": True,
    },
}

MESES_ABREV = {
    1: "Jan", 2: "Fev", 3: "Mar", 4: "Abr", 5: "Mai", 6: "Jun",
    7: "Jul", 8: "Ago", 9: "Set", 10: "Out", 11: "Nov", 12: "Dez",
}
