# -*- coding: utf-8 -*-
"""Configuração da Central de Conferências por modalidade (5152–5160)."""

CONF = {
    "lotofacil": {
        "key": "lotofacil",
        "nome": "Lotofácil",
        "dezena_min": 1,
        "dezena_max": 25,
        "pick_min": 15,
        "pick_max": 20,
        "combo_size": 15,
        "sorteio_model": ("models.sorteio_lotofacil", "SorteioLotofacil"),
        "dezenas_method": "dezenas",
        "menu_hist_desc": "Confere apostas vs. sorteios — 11 a 15 acertos",
        "menu_conv_desc": "TXT ↔ JSON (15 a 20 dezenas)",
        "faixas": [
            (15, "15 acertos"),
            (14, "14 acertos"),
            (13, "13 acertos"),
            (12, "12 acertos"),
            (11, "11 acertos"),
        ],
        "exemplo_txt": "01 02 03 04 05 06 07 08 09 10 11 12 13 14 15",
    },
    "supersete": {
        "key": "supersete",
        "nome": "Super Sete",
        "dezena_min": 0,
        "dezena_max": 9,
        "pick_min": 7,
        "pick_max": 7,
        "combo_size": 7,
        "sorteio_model": ("models.sorteio_supersete", "SorteioSuperSete"),
        "dezenas_method": "digitos",
        "scoring": "positional",
        "menu_hist_desc": "Confere apostas vs. sorteios por coluna (3 a 7 acertos)",
        "menu_conv_desc": "TXT ↔ JSON (7 dígitos, 0–9; repetição permitida)",
        "faixas": [
            (7, "7 acertos"),
            (6, "6 acertos"),
            (5, "5 acertos"),
            (4, "4 acertos"),
            (3, "3 acertos"),
        ],
        "exemplo_txt": "1 2 3 4 5 6 7",
    },
    "lotomania": {
        "key": "lotomania",
        "nome": "Lotomania",
        "dezena_min": 0,
        "dezena_max": 99,
        "pick_min": 50,
        "pick_max": 50,
        "combo_size": 20,
        "sorteio_model": ("models.sorteio_lotomania", "SorteioLotomania"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere apostas vs. sorteios — 20 dezenas",
        "menu_conv_desc": "TXT ↔ JSON (50 dezenas)",
        "faixas": [(20, "20 acertos"), (19, "19 acertos"), (18, "18 acertos")],
        "exemplo_txt": "00 05 10 … (50 números)",
    },
    "quina": {
        "key": "quina",
        "nome": "Quina",
        "dezena_min": 1,
        "dezena_max": 80,
        "pick_min": 5,
        "pick_max": 15,
        "combo_size": 5,
        "sorteio_model": ("models.sorteio_quina", "SorteioQuina"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere apostas vs. sorteios — Quina, Quadra, Terno",
        "menu_conv_desc": "TXT ↔ JSON (5 a 15 dezenas)",
        "faixas": [
            (5, "Quina (5)"),
            (4, "Quadra (4)"),
            (3, "Terno (3)"),
            (2, "Duque (2)"),
        ],
        "exemplo_txt": "03 15 22 33 45",
    },
    "megasena": {
        "key": "megasena",
        "nome": "Mega-Sena",
        "dezena_min": 1,
        "dezena_max": 60,
        "pick_min": 6,
        "pick_max": 20,
        "combo_size": 6,
        "sorteio_model": ("models.sorteio_megasena", "SorteioMegaSena"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere apostas vs. sorteios — Sena, Quina, Quadra",
        "menu_conv_desc": "TXT ↔ JSON (6 a 20 dezenas)",
        "faixas": [(6, "Sena (6)"), (5, "Quina (5)"), (4, "Quadra (4)")],
        "exemplo_txt": "03 15 22 33 45 60",
    },
    "maismilionaria": {
        "key": "maismilionaria",
        "nome": "+Milionária",
        "dezena_min": 1,
        "dezena_max": 50,
        "pick_min": 6,
        "pick_max": 12,
        "combo_size": 6,
        "sorteio_model": ("models.sorteio_maismilionaria", "SorteioMaisMilionaria"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere dezenas + trevos vs. sorteios",
        "menu_conv_desc": "TXT ↔ JSON (6 a 12 dezenas)",
        "faixas": [(6, "6 dez"), (5, "5 dez"), (4, "4 dez")],
        "exemplo_txt": "03 15 22 33 45 50",
    },
    "duplasena": {
        "key": "duplasena",
        "nome": "Dupla Sena",
        "dezena_min": 1,
        "dezena_max": 50,
        "pick_min": 6,
        "pick_max": 15,
        "combo_size": 6,
        "sorteio_model": ("models.sorteio_duplasena", "SorteiosDuplaSena"),
        "dezenas_method": "sorteio1_lista",
        "menu_hist_desc": "Confere apostas vs. 1º sorteio",
        "menu_conv_desc": "TXT ↔ JSON (6 a 15 dezenas)",
        "faixas": [(6, "Sena"), (5, "Quina"), (4, "Quadra")],
        "exemplo_txt": "03 15 22 33 45 50",
    },
    "timemania": {
        "key": "timemania",
        "nome": "Timemania",
        "dezena_min": 1,
        "dezena_max": 80,
        "pick_min": 10,
        "pick_max": 10,
        "combo_size": 10,
        "sorteio_model": ("models.sorteio_timemania", "SorteioTimemania"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere apostas vs. sorteios — 10 dezenas",
        "menu_conv_desc": "TXT ↔ JSON (10 dezenas)",
        "faixas": [(10, "10 acertos"), (9, "9 acertos"), (8, "8 acertos")],
        "exemplo_txt": "03 08 15 22 28 33 40 45 52 60",
    },
    "diasorte": {
        "key": "diasorte",
        "nome": "Dia de Sorte",
        "dezena_min": 1,
        "dezena_max": 31,
        "pick_min": 7,
        "pick_max": 15,
        "combo_size": 7,
        "sorteio_model": ("models.sorteio_diadesorte", "SorteioDiaDeSorte"),
        "dezenas_method": "dezenas_lista",
        "menu_hist_desc": "Confere apostas vs. sorteios — 7 dez + mês",
        "menu_conv_desc": "TXT ↔ JSON (7 a 15 dezenas)",
        "faixas": [(7, "7 acertos"), (6, "6 acertos"), (5, "5 acertos"), (4, "4 acertos")],
        "exemplo_txt": "03 08 15 22 28 33 45",
    },
}


def get_conf(key: str) -> dict:
    if key not in CONF:
        raise ValueError(f"Modalidade conferência inválida: {key}")
    return CONF[key]
