# -*- coding: utf-8 -*-
"""Config da tabela Sorteios e premiação (UI no padrão Dia de Sorte)."""
from __future__ import annotations

PREMIACAO_UI = {
    "lotofacil": {
        "nome": "Lotofácil",
        "nBolas": 15,
        "pad": 2,
        "labelBola": "P",
        "extra": None,
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["15 acertos", "14 acertos", "13 acertos", "12 acertos", "11 acertos"],
    },
    "megasena": {
        "nome": "Mega-Sena",
        "nBolas": 6,
        "pad": 2,
        "labelBola": "P",
        "extra": None,
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["6 acertos", "5 acertos", "4 acertos"],
    },
    "quina": {
        "nome": "Quina",
        "nBolas": 5,
        "pad": 2,
        "labelBola": "P",
        "extra": None,
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["5 acertos", "4 acertos", "3 acertos", "2 acertos"],
    },
    "lotomania": {
        "nome": "Lotomania",
        "nBolas": 20,
        "pad": 2,
        "labelBola": "P",
        "extra": None,
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["20 acertos", "19 acertos", "18 acertos", "17 acertos", "16 acertos", "15 acertos", "0 acertos"],
    },
    "timemania": {
        "nome": "Timemania",
        "nBolas": 7,
        "pad": 2,
        "labelBola": "P",
        "extra": "time",
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["7 acertos", "6 acertos", "5 acertos", "4 acertos", "3 acertos", "Time"],
    },
    "duplasena": {
        "nome": "Dupla Sena",
        "nBolas": 6,
        "pad": 2,
        "labelBola": "S1",
        "extra": "dupla",
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["S1 6 acertos", "S1 5 acertos", "S1 4 acertos", "S1 3 acertos", "S2 6 acertos", "S2 5 acertos", "S2 4 acertos", "S2 3 acertos"],
    },
    "maismilionaria": {
        "nome": "+Milionária",
        "nBolas": 6,
        "pad": 2,
        "labelBola": "P",
        "extra": "trevos",
        "ordenar": True,
        "fonte": "excel",
        "faixas": ["6+2 trevos", "6 dez", "5+2 trevos", "5 dez", "4+2 trevos", "4 dez", "3+2 trevos", "3+1 trevo", "2+2 trevos", "2+1 trevo"],
    },
    "supersete": {
        "nome": "Super Sete",
        "nBolas": 7,
        "pad": 1,
        "labelBola": "C",
        "extra": None,
        "ordenar": False,
        "fonte": "excel",
        "faixas": ["7 acertos", "6 acertos", "5 acertos", "4 acertos", "3 acertos"],
    },
}
