# -*- coding: utf-8 -*-
"""Configuração da comparação visual entre concursos — por modalidade."""

COMPARE_MODALITIES = {
    "lotofacil": {
        "nome": "Lotofácil",
        "model_module": "models.sorteio_lotofacil",
        "model_class": "SorteioLotofacil",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 25,
        "grid_cols": 5,
        "volante_max_width": 320,
        "cell_font_rem": 0.58,
        "modos": ["volante", "posicional", "hibrido"],
        "ordered_fields": [f"posicao_{i}" for i in range(1, 16)],
        "set_from_ordered": True,
        "subtitle": "15 dezenas (01–25) · ordem de sorteio",
    },
    "lotomania": {
        "nome": "Lotomania",
        "model_module": "models.sorteio_lotomania",
        "model_class": "SorteioLotomania",
        "layout": "grid",
        "dezena_min": 0,
        "dezena_max": 99,
        "grid_cols": 10,
        "volante_max_width": 340,
        "cell_font_rem": 0.52,
        "modos": ["volante", "posicional", "hibrido"],
        "ordered_fields": [f"d{i:02d}" for i in range(1, 21)],
        "set_from_ordered": True,
        "subtitle": "20 dezenas sorteadas (00–99) · grade 10×10",
    },
    "quina": {
        "nome": "Quina",
        "model_module": "models.sorteio_quina",
        "model_class": "SorteioQuina",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 80,
        "grid_cols": 10,
        "volante_max_width": 320,
        "cell_font_rem": 0.58,
        "modos": ["volante"],
        "ordered_fields": ["d1", "d2", "d3", "d4", "d5"],
        "set_from_ordered": True,
        "set_method": "dezenas",
        "display_method": "dezenas_lista",
        "subtitle": "5 dezenas sorteadas (01–80) · comparação por conjunto",
    },
    "megasena": {
        "nome": "Mega-Sena",
        "model_module": "models.sorteio_megasena",
        "model_class": "SorteioMegaSena",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 60,
        "grid_cols": 10,
        "volante_max_width": 300,
        "cell_font_rem": 0.62,
        "modos": ["volante"],
        "ordered_fields": ["d1", "d2", "d3", "d4", "d5", "d6"],
        "set_from_ordered": True,
        "set_method": "dezenas",
        "display_method": "dezenas_lista",
        "subtitle": "6 dezenas sorteadas (01–60) · volante 6×10",
    },
    "duplasena": {
        "nome": "Dupla Sena",
        "model_module": "models.sorteio_duplasena",
        "model_class": "SorteiosDuplaSena",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 50,
        "grid_cols": 10,
        "volante_max_width": 280,
        "cell_font_rem": 0.62,
        "modos": ["volante"],
        "dual_sorteio": True,
        "sorteio1_set": "sorteio1",
        "sorteio1_list": "sorteio1_lista",
        "sorteio2_set": "sorteio2",
        "sorteio2_list": "sorteio2_lista",
        "subtitle": "6 dezenas por sorteio (01–50) · escolha 1º ou 2º sorteio",
    },
    "maismilionaria": {
        "nome": "+Milionária",
        "model_module": "models.sorteio_maismilionaria",
        "model_class": "SorteioMaisMilionaria",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 50,
        "grid_cols": 10,
        "volante_max_width": 280,
        "cell_font_rem": 0.62,
        "modos": ["volante"],
        "ordered_fields": ["d1", "d2", "d3", "d4", "d5", "d6"],
        "set_from_ordered": True,
        "set_method": "dezenas",
        "display_method": "dezenas_lista",
        "extra_trevos": True,
        "trevo_min": 1,
        "trevo_max": 6,
        "trevo_set_method": "trevos",
        "trevo_list_method": "trevos_lista",
        "subtitle": "6 dezenas + 2 trevos · comparação separada",
    },
    "timemania": {
        "nome": "Timemania",
        "model_module": "models.sorteio_timemania",
        "model_class": "SorteioTimemania",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 80,
        "grid_cols": 10,
        "volante_max_width": 320,
        "cell_font_rem": 0.58,
        "modos": ["volante"],
        "ordered_fields": [f"d{i}" for i in range(1, 11)],
        "set_from_ordered": True,
        "set_method": "dezenas",
        "display_method": "dezenas_lista",
        "extra_time": True,
        "time_max": 80,
        "subtitle": "Dezenas sorteadas + Time do Coração",
    },
    "supersete": {
        "nome": "Super Sete",
        "model_module": "models.sorteio_supersete",
        "model_class": "SorteioSuperSete",
        "layout": "colunas",
        "colunas": 7,
        "digito_min": 0,
        "digito_max": 9,
        "dezena_min": 0,
        "dezena_max": 9,
        "modos": ["posicional"],
        "ordered_fields": [f"coluna_{i}" for i in range(1, 8)],
        "set_from_ordered": True,
        "subtitle": "7 colunas · dígitos 0–9 · repetição por coluna",
    },
    "diadesorte": {
        "nome": "Dia de Sorte",
        "model_module": "models.sorteio_diadesorte",
        "model_class": "SorteioDiaDeSorte",
        "layout": "grid",
        "dezena_min": 1,
        "dezena_max": 31,
        "grid_cols": 10,
        "volante_rows": [[1, 10], [11, 20], [21, 30], [31, 31]],
        "volante_solo_col": 1,
        "volante_max_width": 320,
        "cell_font_rem": 0.62,
        "modos": ["volante", "posicional", "hibrido"],
        "ordered_fields": ["d1", "d2", "d3", "d4", "d5", "d6", "d7"],
        "set_from_ordered": True,
        "extra_mes": True,
        "mes_field": "mes_num",
        "mes_label_field": "mes_nome",
        "subtitle": "7 dezenas (01–31) + Mês da Sorte · ordem de sorteio",
    },
}


def get_compare_config(modality_key: str) -> dict:
    if modality_key not in COMPARE_MODALITIES:
        raise ValueError(f"Modalidade sem comparar configurado: {modality_key}")
    cfg = dict(COMPARE_MODALITIES[modality_key])
    cfg["key"] = modality_key
    return cfg
